name: sleep_diary_mobile
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  numberpicker: ^2.1.2
  syncfusion_flutter_charts: ^25.1.42+1
  feather_icons: ^1.2.0
  cupertino_icons: ^1.0.6
  # table_calendar: ^3.1.0
  flutter_native_splash: 2.3.10
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  get: ^4.6.6
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.3
  flutter_timezone: ^1.0.8
  persistent_bottom_nav_bar: ^5.0.2
  flutter_calendar_carousel: ^2.4.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
